{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test_feature_story.TestLogin object at 0x10eb697c0>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failure(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert \"1\" == 1\nE           AssertionError: assert '1' == 1\n\ntest_feature_story.py:30: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1587612663261, "stop": 1587612663261}, {"name": "点击密码", "status": "passed", "start": 1587612663261, "stop": 1587612663261}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"/Users/mac/PycharmProjects/python_base/allure/test_feature_story.py\", line 30, in test_login_failure\n    assert \"1\" == 1\n"}, "start": 1587612663261, "stop": 1587612663261}], "attachments": [{"name": "stdout", "source": "4f7290e2-ccb3-4465-8582-626a3e51d07b-attachment.txt", "type": "text/plain"}], "start": 1587612663261, "stop": 1587612663261, "uuid": "07a549a8-aa40-4de3-aeea-d8c01b519ea9", "historyId": "a58c5550e5c40eb80abda2e84e87077a", "testCaseId": "a0fb827149424dbc77d431148fe9f888", "fullName": "test_feature_story.TestLogin#test_login_failure", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "密码缺失"}, {"name": "suite", "value": "test_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "mac-lee.local"}, {"name": "thread", "value": "10663-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_story"}]}